language: node_js

node_js: "node"

before_script:
  - npm install -g truffle ganache-cli
  - npm install

script: 
  - ganache-cli -m=plasma_mvp > /dev/null &
  - sleep 5
  - truffle migrate
  - truffle test
